# Generated by Django 2.2.6 on 2019-10-07 10:52

import pyuploadcare.dj.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=pyuploadcare.dj.models.ImageGroupField(null=True),
        ),
    ]
