# Generated by Django 2.1.5 on 2019-04-24 09:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('800ce6b8-0e76-4f40-854f-7af4141b34cf'), editable=False,
                                        primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('state', models.CharField(default='init', max_length=4)),
                ('date_due', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_info',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.UserCheckoutInfo')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ordersapp.Order')),
            ],
            options={
                'verbose_name': 'Order Information',
                'verbose_name_plural': 'Order Information',
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordersapp.Order')),
                (
                'product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.ProductDesign')),
            ],
            options={
                'verbose_name': ' Product Order',
            },
        ),
    ]
