# Generated by Django 3.0.2 on 2020-01-28 20:52

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='3Y4NCaByTbPpABPkLHmVo5', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
