# Generated by Django 3.0.2 on 2020-01-31 07:04

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200128_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='LdcexVPgT77V93v2ZGz8fG', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
