# Generated by Django 2.1.5 on 2019-04-24 10:17

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ordersapp', '0002_order_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('72ef9dde-7bcd-4dd5-9535-058a055eb72a'), editable=False,
                                   primary_key=True, serialize=False),
        ),
    ]
