# Generated by Django 3.0.3 on 2020-03-03 19:00

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200303_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='W46b2ej8WSnYx6vdrYm96H', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
