# Generated by Django 2.1.5 on 2019-05-03 05:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ordersapp', '0003_auto_20190424_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('618538bb-beda-408c-ab01-6c85cd767d1a'), editable=False,
                                   primary_key=True, serialize=False),
        ),
    ]
