# Generated by Django 3.0.3 on 2020-03-03 19:09

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200303_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='MJHRFKqc86CnamFafpz33G', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
