# Generated by Django 2.1.5 on 2019-05-03 05:14

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ordersapp', '0004_auto_20190503_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aeefdf05-2d6f-4cd9-a5b0-24d1ce939495'), editable=False,
                                   primary_key=True, serialize=False),
        ),
    ]
