# Generated by Django 3.0.3 on 2020-03-04 14:32

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200303_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='CdpPJrBAMgeQrEtaMEqgkn', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
