# Generated by Django 3.0.3 on 2020-03-13 13:10

from django.db import migrations
import djmoney.models.fields
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200304_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='P6JMazM5DPsG8VfTN9VoBj', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='price_on_purchase_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('KES', 'Kenyan Shilling')], default='XYZ', editable=False, max_length=3),
        ),
    ]
