# Generated by Django 2.1.5 on 2019-05-03 09:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ordersapp', '0005_auto_20190503_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('52e49156-94ee-42ab-a10c-d2d6e5773418'), editable=False,
                                   primary_key=True, serialize=False),
        ),
    ]
