# Generated by Django 3.0.4 on 2020-03-18 10:51

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200313_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='R8yGxgqhmRYaPCh9Jgn6EP', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
