# Generated by Django 2.1.5 on 2019-05-03 10:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ordersapp', '0007_auto_20190503_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('811768d0-e45e-49a7-b24b-3ee6f1dcf4a2'), editable=False,
                                   primary_key=True, serialize=False),
        ),
    ]
