# Generated by Django 2.1.5 on 2019-05-03 10:16

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ordersapp', '0008_auto_20190503_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('be7e1d00-3a80-4335-bd0d-9b55cbfe1039'), editable=False,
                                   primary_key=True, serialize=False),
        ),
    ]
