# Generated by Django 2.1.5 on 2019-05-03 10:16

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ordersapp', '0009_auto_20190503_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('94d709a9-9427-4caa-a9fb-acf3122d8266'), editable=False,
                                   primary_key=True, serialize=False),
        ),
    ]
