# Generated by Django 3.0.6 on 2020-05-29 20:46

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200522_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='7tnv2NXYjerdb4YcgqZyeA', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
