# Generated by Django 2.1.5 on 2019-05-03 13:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ordersapp', '0010_auto_20190503_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fba476c8-7a46-47b9-b861-3692c03e1b2c'), editable=False,
                                   primary_key=True, serialize=False),
        ),
    ]
