# Generated by Django 3.0.6 on 2020-06-05 14:47

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200605_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='Chs6cLvb934nsufNmEFvDq', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SendyDeliveryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendy_order_no', models.CharField(max_length=255)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
    ]
