# Generated by Django 2.1.5 on 2019-05-04 22:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ordersapp', '0011_auto_20190503_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='state',
            field=models.CharField(
                choices=[('init', 'Ordered'), ('pend', 'Pending'), ('del', 'Delivery'), ('proc', 'Processed')],
                default='init', max_length=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c54541c2-9eae-4ec0-affc-e3ebdc6f6d0e'), editable=False,
                                   primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(
                choices=[('init', 'Ordered'), ('pend', 'Pending'), ('del', 'Delivery'), ('proc', 'Processed')],
                default='init', max_length=4),
        ),
    ]
