# Generated by Django 2.1.5 on 2019-05-04 22:54

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ordersapp', '0012_auto_20190505_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aa3a35cc-547f-46ed-b68e-97279c39b88b'), editable=False,
                                   primary_key=True, serialize=False),
        ),
    ]
