# Generated by Django 2.1.5 on 2019-05-04 22:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ordersapp', '0013_auto_20190505_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fec1968b-365b-4c9c-9681-f2f3c77a1a50'), editable=False,
                                   primary_key=True, serialize=False),
        ),
    ]
