# Generated by Django 2.1.5 on 2019-05-05 10:32

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ordersapp', '0014_auto_20190505_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='address_info',
            new_name='user_info',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4bb04c75-ca18-4fd4-94b9-db25a96d549b'), editable=False,
                                   primary_key=True, serialize=False),
        ),
    ]
