# Generated by Django 2.1.5 on 2019-05-05 15:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ordersapp', '0015_auto_20190505_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e28a5fba-14b8-49fa-8ddd-f0bfb45dcb7f'), editable=False,
                                   primary_key=True, serialize=False),
        ),
    ]
