# Generated by Django 2.1.5 on 2019-05-05 17:36

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ordersapp', '0016_auto_20190505_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fb2d2e9c-aac4-42ca-833b-ad69586743cd'), editable=False,
                                   primary_key=True, serialize=False),
        ),
    ]
