# Generated by Django 2.1.5 on 2019-05-05 17:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ordersapp', '0017_auto_20190505_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c1f41bcf-2366-4d08-ae78-a05dfeda5f67'), editable=False,
                                   primary_key=True, serialize=False),
        ),
    ]
