# Generated by Django 3.0.3 on 2020-03-13 13:10

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('KES', 'Kenyan Shilling')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_base_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('KES', 'Kenyan Shilling')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('KES', 'Kenyan Shilling')], default='XYZ', editable=False, max_length=3),
        ),
    ]
