# Generated by Django 2.2.6 on 2019-10-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(editable=False, max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Department',
            },
        ),
    ]
