# Generated by Django 3.0.7 on 2020-06-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='contact_name',
            field=models.CharField(default='Daniel Waruo', max_length=100),
            preserve_default=False,
        ),
    ]
