from django.db import models

"""
The department should not be autogenerated 
-create a department
-link it to the apps dealing with those departments
-restrict access to the api-endpoints based on whether a user is allowed to access the end points 
"""


class Department(models.Model):
    """
    Department are a generic way  of limiting access to certain apps
    """
    app_label = models.CharField(max_length=100, editable=False)
    name = models.CharField(max_length=100, null=True)

    class Meta:
        verbose_name = 'Department'

    def save(self, *args, **kwargs):
        if kwargs.get("name", None):
            self.name = kwargs.get("name")
        elif not kwargs.get("name", None):
            if not self.name:
                self.name = self.app_label.split(".")[-1]
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name + " Department"
