from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from accounts.models import User

"""
The department should not be autogenerated 
-create a department
-link it to the apps dealing with those departments
-restrict access to the api-endpoints based on whether a user is allowed to access the end points 
"""


class Department(models.Model):
    """
    Department are a generic way  of limiting access to certain apps
    """
    app_label = models.CharField(max_length=100, editable=False)
    name = models.CharField(max_length=100, null=True)

    class Meta:
        verbose_name = 'Department'
        permissions = (
            # permission held by staff_account department users
            ('add_staff', "Can add staff to a department"),
            # department_manager permissions and general manager perms
            ('set_permissions', "Set permissions of a Departmental staff"),
            ('include_department', "Add a department to a staff's access"),
            # general manager permissions
            ('manage_department_manager', "Manage the access of a Departmental Manager"),
            # super user permissions
            ('edit_departments', "Can edit the name of a Department"),
            ('manage_general_manager', "Manage the access of a General Manager"),
        )

    def save(self, *args, **kwargs):
        if kwargs.get("name", None):
            self.name = kwargs.get("name")
        elif not kwargs.get("name", None):
            if not self.name:
                self.name = self.app_label
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name + " Department"


STAFF_TYPES = (
    (0, "Department Staff"),
    (1, "Department Manager"),
    (2, "General Manager")
)


class StaffUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    departments = models.ManyToManyField(to=Department)
    staff_type = models.PositiveSmallIntegerField(choices=STAFF_TYPES)

    def __str__(self):
        return self.user.username

    def save(self, **kwargs):
        user = super().save(**kwargs)
        return user


@receiver(post_save, sender=StaffUser)
def give_permissions(**kwargs):
    staff_user = kwargs["instance"]
    if staff_user.staff_type == 1:
        from business.authorization.utils import set_department_manager_perms
        department_ids = list(map(
            lambda department: department.id,
            staff_user.departments.all()
        ))
        set_department_manager_perms(staff_user.user.id, department_ids)
    elif staff_user.staff_type == 2:
        from business.authorization.utils import set_general_manager_perms
        department_ids = list(map(
            lambda department: department.id,
            staff_user.departments.all()
        ))
        set_general_manager_perms(staff_user.user.id, department_ids)