# Generated by Django 2.2.6 on 2019-10-14 10:55

import django.db.models.deletion
from django.db import migrations, models

import utils.session.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qsessions', '0002_session_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('session_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qsessions.Session')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'abstract': False,
            },
            bases=('qsessions.session',),
            managers=[
                ('objects', utils.session.models.CheckoutSessionManager()),
            ],
        ),
    ]
