# Generated by Django 3.0.3 on 2020-03-13 13:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200218_1007'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qsessions', '0002_session_created_at'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckoutSession',
            new_name='AnonymousSession',
        ),
    ]
