# Generated by Django 3.0.2 on 2020-01-28 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('37ef15dc-ce96-4783-8afc-82ca4b893c33'), primary_key=True, serialize=False),
        ),
    ]
