# Generated by Django 3.0.3 on 2020-03-03 19:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200303_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('48a2175e-860a-4bd3-a7df-a53c7826a28c'), primary_key=True, serialize=False),
        ),
    ]
