# Generated by Django 2.2.6 on 2019-10-07 10:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0003_auto_20191007_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a651fb58-2e6b-4bbb-a90a-73cc59c9a977'), primary_key=True,
                                   serialize=False),
        ),
    ]
