# Generated by Django 3.0.2 on 2020-02-07 08:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200131_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('64875a59-3ea3-4677-9490-a711476e508f'), primary_key=True, serialize=False),
        ),
    ]
