# Generated by Django 2.2.6 on 2019-10-07 10:53

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0004_auto_20191007_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2a1cd9ac-9a9e-4a09-9572-6db41304475d'), primary_key=True,
                                   serialize=False),
        ),
    ]
