# Generated by Django 2.2.6 on 2019-10-07 10:53

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0005_auto_20191007_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('75f9b64c-85be-4406-af2f-88836c831a47'), primary_key=True,
                                   serialize=False),
        ),
    ]
