# Generated by Django 3.0.4 on 2020-03-18 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200313_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('49266f7d-fab0-40b7-8523-a56fe6ba429c'), primary_key=True, serialize=False),
        ),
    ]
