# Generated by Django 2.2.6 on 2019-10-07 13:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0007_auto_20191007_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('58d1999e-639d-4966-b825-aa56fab96d00'), primary_key=True,
                                   serialize=False),
        ),
    ]
