# Generated by Django 3.0.4 on 2020-03-24 10:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200318_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('45620f32-805d-4ad1-9f47-4359c5198e9c'), primary_key=True, serialize=False),
        ),
    ]
