# Generated by Django 3.0.4 on 2020-05-22 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20200324_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c38296e2-1e4a-40a9-a7f5-a6c731724746'), primary_key=True, serialize=False),
        ),
    ]
