# Generated by Django 2.2.6 on 2019-10-07 14:53

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0008_auto_20191007_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5dffb470-16a4-4af2-ba69-6e956e5d2595'), primary_key=True,
                                   serialize=False),
        ),
    ]
