# Generated by Django 3.0.6 on 2020-05-29 20:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20200522_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('771b8d58-f2c7-493c-a804-d04c79b145fc'), primary_key=True, serialize=False),
        ),
    ]
