# Generated by Django 2.2.6 on 2019-10-07 15:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0009_auto_20191007_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c03d42cf-e1e8-4031-b7a1-be4a930e71d8'), primary_key=True,
                                   serialize=False),
        ),
    ]
