# Generated by Django 3.0.6 on 2020-06-05 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20200529_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fe175415-a507-4b56-b472-5489d0e5996e'), primary_key=True, serialize=False),
        ),
    ]
