# Generated by Django 3.0.6 on 2020-06-05 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20200605_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('66743153-96de-4e24-b7f8-00a5e03521ca'), primary_key=True, serialize=False),
        ),
    ]
